# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/pept_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 320)
        self.Dialog = Dialog
        self.done = QtWidgets.QPushButton(Dialog)
        self.done.setGeometry(QtCore.QRect(60, 250, 90, 25))
        self.done.setObjectName("done")
        self.delete = QtWidgets.QPushButton(Dialog)
        self.delete.setGeometry(QtCore.QRect(155, 250, 90, 25))
        self.delete.setObjectName("delete")
        self.pause = QtWidgets.QPushButton(Dialog)
        self.pause.setGeometry(QtCore.QRect(155, 280, 90, 25))
        self.pause.setObjectName("pause")
        self.Cancel = QtWidgets.QPushButton(Dialog)
        self.Cancel.setGeometry(QtCore.QRect(250, 250, 90, 25))
        self.Cancel.setObjectName("Cancel")
        self.checkplot_before = QtWidgets.QCheckBox(Dialog)
        self.checkplot_before.setGeometry(QtCore.QRect(80, 210, 111, 23))
        self.checkplot_before.setObjectName("checkplot_before")
        self.checkplot_after = QtWidgets.QCheckBox(Dialog)
        self.checkplot_after.setGeometry(QtCore.QRect(200, 210, 111, 23))
        self.checkplot_after.setObjectName("checkplot_after")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PEPT Editor"))
        self.done.setText(_translate("Dialog", "Done"))
        self.Cancel.setText(_translate("Dialog", "Cancel"))
        self.delete.setText(_translate("Dialog", "Delete"))
        self.pause.setText(_translate("Dialog", "Pause"))
        self.checkplot_before.setText(_translate("Dialog", "Plot before"))
        self.checkplot_after.setText(_translate("Dialog", "Plot after"))
